package com.pipai.wf.unit.ability;

public enum AbilityType {

	FIRE_ACTUALIZATION,
	WATER_ACTUALIZATION,
	EARTH_ACTUALIZATION,
	ELECTRIC_ACTUALIZATION,
	LIGHT_ACTUALIZATION,
	FORCE_ACTUALIZATION,
	FIREBALL,
	WATER_BLAST,
	REGENERATION,
	QUICK_RELOAD,
	PRECISION_SHOT
	;

}
